language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "14"
  - "12"

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6.14.12; fi

script:
   - npm run standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
